name: Build and Push Docker Web Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite disparar manualmente

jobs:
  build:
    name: Build Web Image
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{ steps.build-image.outputs.image_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/habitos:${{ steps.vars.outputs.short_sha }}
          output: type=image,name=${{ secrets.DOCKER_USERNAME }}/habitos:${{ steps.vars.outputs.short_sha }},push=false
          labels: |
            org.opencontainers.image.revision=${{ steps.vars.outputs.short_sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

  push:
    name: Push Web Image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code (again, to be sure)
        uses: actions/checkout@v4

      - name: Check directory
        run: |
          pwd
          ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: . # Importante: Definir o contexto correto
          file: ./Dockerfile # Importante: Definir o Dockerfile correto
          input: ${{ needs.build.outputs.image_id }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/habitos:${{ steps.vars.outputs.short_sha }}

      - name: Tag latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/habitos:${{ steps.vars.outputs.short_sha }} ${{ secrets.DOCKER_USERNAME }}/habitos:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/habitos:latest